# Generated by Django 5.2 on 2025-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertingAndNotificationPlatform', '0002_alert_alertrecipient_alertstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
